spring:
  application:
    name: watch-cluster

logging:
  level:
    com.watchcluster: INFO
    com.watchcluster.util.CronScheduler: INFO
    io.fabric8.kubernetes: WARN
    okhttp3: WARN
    com.github.dockerjava: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
management:
  health:
    probes:
      enabled: false


# Application info
info:
  app:
    name: watch-cluster
    description: Kubernetes deployment image update monitor
    version: "1.0.0"
