apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watch-cluster
  namespace: kube-system
  labels:
    app: watch-cluster
spec:
  selector:
    matchLabels:
      app: watch-cluster
  template:
    metadata:
      labels:
        app: watch-cluster
    spec:
      serviceAccountName: watch-cluster
      containers:
      - name: watch-cluster
        image: watch-cluster:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule