apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-cluster
  namespace: watch-cluster
  labels:
    app: watch-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-cluster
  template:
    metadata:
      labels:
        app: watch-cluster
    spec:
      serviceAccountName: watch-cluster
      containers:
      - name: watch-cluster
        image: hub.sixtyfive.me/watch-cluster:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      imagePullSecrets:
        - name: regcred
