apiVersion: v1
kind: ServiceAccount
metadata:
  name: watch-cluster
  namespace: watch-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-cluster
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watch-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watch-cluster
subjects:
- kind: ServiceAccount
  name: watch-cluster
  namespace: watch-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: watch-cluster
  name: watch-cluster-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-cluster-secrets
  namespace: watch-cluster
subjects:
- kind: ServiceAccount
  name: watch-cluster
  namespace: watch-cluster
roleRef:
  kind: Role
  name: watch-cluster-secrets
  apiGroup: rbac.authorization.k8s.io